In [1]:
import random

In [2]:
a = random.random()
a #a random float in the range from 0.0 to 1.0

0.11481705144450716

In [3]:
a = random.uniform(1,10) #if you want to specify a range
a #a random float in this range

5.52214024691293

In [4]:
a = random.randint(1,10) #if you want to have an integer
a

6

In [5]:
a = random.randrange(1,10) #same as randint but here the upper bound is not included
a

8

In [6]:
a = random.normalvariate(0, 1)
#picks a random value from a normql distribution with a mean of 0 and a standard deviation of 1
a

-1.626255226347304

In [7]:
mylist = list("ABCDEFG")
mylist

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [8]:
a = random.choice(mylist) #picks 1 random element from mylist
a

'D'

In [9]:
a = random.sample(mylist, 3)
#picks 3 elements without replacement
a

['A', 'E', 'B']

In [10]:
a = random.choices(mylist, k=3)
#picks 3 elements with replacement
a

['D', 'D', 'F']

In [11]:
random.shuffle(mylist)
mylist

['F', 'E', 'C', 'A', 'G', 'D', 'B']

In [15]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


In [16]:
random.seed(1)
print(random.random())
print(random.randint(1,10))

0.13436424411240122
2


Exactly the same numbers because they have the same seed.

Because this numbers are reproducible, they are not recommended to use for security purposes. You should use the secrets module instead.

In [19]:
import secrets

In [21]:
a = secrets.randbelow(10) #produces a random integer in the range from 0 to 10 (excluded)
a

2

In [22]:
a = secrets.randbits(4) #returns an integer with 4 random bits
#in this case the highest possible number here in this case would be 1111 (2**3 + 2**2 + 2**1 + 2**0 = 15)
#will generate a random number in the range from 0 to 15
a

14

In [23]:
mylist = list("ABCDEFG")
a = secrets.choice(mylist) #pick a random choice that is not reproducible
a

'E'

In [24]:
import numpy as np

In [25]:
a = np.random.rand(3) #produces a 1D array with 3 elements that are random float
a

array([0.7093951 , 0.78189116, 0.44106914])

In [26]:
a = np.random.randint(0, 10, 3)
#produces a 1D array with 3 elements that are integers between 0 and 10 (excluded)
a

array([3, 7, 1])

In [27]:
a = np.random.randint(0, 10, (3, 4))
a

array([[1, 5, 7, 4],
       [7, 7, 7, 0],
       [4, 3, 2, 4]])

In [35]:
np.random.shuffle(a)
#shuffles the elements along the 1st axis
a

array([[4, 3, 2, 4],
       [1, 5, 7, 4],
       [7, 7, 7, 0]])

In [38]:
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


In [39]:
np.random.seed(1)
print(np.random.rand(3,3))

[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


Same array